import type { RandomIdleConfig } from './randomIdle.types';

export const RANDOM_IDLE_DEFAULTS = {
  minInterval: 5_000,
  maxInterval: 10_000,
  behaviorProbabilities: {
    longBlink: 0.3,
    slowLookAround: 0.3,
    smallUpwardGlance: 0.2,
    smallDownwardGlance: 0.2,
  },
  longBlinkOptions: {
    closingDuration: 0.1,
    closedHoldDuration: 0.42,
    openingDuration: 0.16,
  },
  slowLookOptions: {
    eyeDistanceX: 4,
    eyeDistanceY: 0,
    eyeOutDuration: 0.38,
    bodyFollowDelay: 0.14,
    bodyDistanceX: 1,
    bodyRotation: 0.1,
    bodyFollowDuration: 0.46,
    directionalHoldDuration: 0.55,
    eyeReturnDuration: 0.4,
    bodyReturnDelay: 0.08,
    bodyReturnDuration: 0.48,
    outwardEase: 'sine.out',
    returnEase: 'sine.inOut',
  },
  upwardGlanceOptions: {
    eyeDistanceX: 0,
    eyeDistanceY: -3,
    eyeOutDuration: 0.32,
    bodyFollowDelay: 0.14,
    bodyDistanceX: 0,
    bodyRotation: 0,
    bodyFollowDuration: 0.4,
    directionalHoldDuration: 0.42,
    eyeReturnDuration: 0.36,
    bodyReturnDelay: 0.08,
    bodyReturnDuration: 0.42,
    outwardEase: 'sine.out',
    returnEase: 'sine.inOut',
  },
  downwardGlanceOptions: {
    eyeDistanceX: 0,
    eyeDistanceY: 3,
    eyeOutDuration: 0.32,
    bodyFollowDelay: 0.14,
    bodyDistanceX: 0,
    bodyRotation: 0,
    bodyFollowDuration: 0.4,
    directionalHoldDuration: 0.42,
    eyeReturnDuration: 0.36,
    bodyReturnDelay: 0.08,
    bodyReturnDuration: 0.42,
    outwardEase: 'sine.out',
    returnEase: 'sine.inOut',
  },
} satisfies RandomIdleConfig;
